// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/Wei-Shaw/sub2api/ent"
	"github.com/Wei-Shaw/sub2api/internal/config"
	"github.com/Wei-Shaw/sub2api/internal/handler"
	"github.com/Wei-Shaw/sub2api/internal/handler/admin"
	"github.com/Wei-Shaw/sub2api/internal/payment"
	"github.com/Wei-Shaw/sub2api/internal/repository"
	"github.com/Wei-Shaw/sub2api/internal/server"
	"github.com/Wei-Shaw/sub2api/internal/server/middleware"
	"github.com/Wei-Shaw/sub2api/internal/service"
	"github.com/redis/go-redis/v9"
	"net/http"
)

import (
	_ "embed"
	_ "github.com/Wei-Shaw/sub2api/ent/runtime"
	_ "net/http/pprof"
)

// Injectors from wire.go:

func initializeApplication(buildInfo handler.BuildInfo) (*Application, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	client, err := repository.ProvideEnt(configConfig)
	if err != nil {
		return nil, err
	}
	db, err := repository.ProvideSQLDB(client)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(client, db)
	redeemCodeRepository := repository.NewRedeemCodeRepository(client)
	redisClient := repository.ProvideRedis(configConfig)
	refreshTokenCache := repository.NewRefreshTokenCache(redisClient)
	settingRepository := repository.NewSettingRepository(client)
	groupRepository := repository.NewGroupRepository(client, db)
	proxyRepository := repository.NewProxyRepository(client, db)
	clusterAdminRepository := repository.NewClusterRepository(db)
	clusterRepository := repository.ProvideClusterRuntimeRepository(clusterAdminRepository)
	clusterCachePublisher := repository.NewClusterCachePublisher(redisClient)
	clusterCacheCoordinator := service.NewClusterCacheCoordinator(configConfig, clusterRepository, clusterCachePublisher)
	settingService := service.ProvideSettingService(settingRepository, groupRepository, proxyRepository, configConfig, clusterCacheCoordinator)
	emailCache := repository.NewEmailCache(redisClient)
	emailService := service.NewEmailService(settingRepository, emailCache)
	turnstileVerifier := repository.NewTurnstileVerifier()
	turnstileService := service.NewTurnstileService(settingService, turnstileVerifier)
	emailQueueService := service.ProvideEmailQueueService(emailService)
	promoCodeRepository := repository.NewPromoCodeRepository(client)
	billingCache := repository.NewBillingCache(redisClient)
	userSubscriptionRepository := repository.NewUserSubscriptionRepository(client)
	apiKeyRepository := repository.NewAPIKeyRepository(client, db)
	userRPMCache := repository.NewUserRPMCache(redisClient)
	userGroupRateRepository := repository.NewUserGroupRateRepository(db)
	billingCacheService := service.ProvideBillingCacheService(billingCache, userRepository, userSubscriptionRepository, apiKeyRepository, userRPMCache, userGroupRateRepository, configConfig)
	accountShareAPIKeyBindingChecker := repository.NewAccountShareModeAPIKeyBindingChecker(client, db)
	usageLogRepository := repository.NewUsageLogRepository(client, db)
	apiKeyCache := repository.NewAPIKeyCache(redisClient)
	concurrencyCache := repository.ProvideConcurrencyCache(redisClient, configConfig)
	schedulerCache := repository.ProvideSchedulerCache(redisClient, configConfig)
	accountRepository := repository.NewAccountRepository(client, db, schedulerCache)
	clusterNodeState := service.NewClusterNodeState(configConfig)
	clusterTaskExecutor := service.NewClusterTaskExecutor(configConfig, clusterRepository, clusterNodeState)
	concurrencyService := service.ProvideConcurrencyService(concurrencyCache, accountRepository, configConfig, clusterTaskExecutor)
	apiKeyService := service.ProvideAPIKeyService(apiKeyRepository, accountShareAPIKeyBindingChecker, userRepository, groupRepository, userSubscriptionRepository, userGroupRateRepository, usageLogRepository, apiKeyCache, configConfig, settingService, billingCacheService, concurrencyService)
	apiKeyAuthCacheInvalidator := service.ProvideAPIKeyAuthCacheInvalidator(apiKeyService)
	promoService := service.NewPromoService(promoCodeRepository, userRepository, billingCacheService, client, apiKeyAuthCacheInvalidator)
	conversationRepository := repository.NewConversationRepository(client)
	conversationService := service.NewConversationService(conversationRepository, userRepository)
	systemNoticeService := service.NewSystemNoticeService(conversationService)
	subscriptionService := service.ProvideSubscriptionService(groupRepository, userSubscriptionRepository, billingCacheService, client, configConfig, systemNoticeService)
	affiliateRepository := repository.NewAffiliateRepository(client, db)
	affiliateService := service.NewAffiliateService(affiliateRepository, settingService, apiKeyAuthCacheInvalidator, billingCacheService)
	userPrivateGroupProvisioner := service.NewUserPrivateGroupService(groupRepository, userRepository, userSubscriptionRepository, subscriptionService, settingService)
	authService := service.ProvideAuthService(client, userRepository, redeemCodeRepository, refreshTokenCache, configConfig, settingService, emailService, turnstileService, emailQueueService, promoService, subscriptionService, affiliateService, userPrivateGroupProvisioner)
	userService := service.NewUserService(userRepository, settingRepository, apiKeyAuthCacheInvalidator, billingCache)
	redeemCache := repository.NewRedeemCache(redisClient)
	redeemService := service.NewRedeemService(redeemCodeRepository, userRepository, subscriptionService, redeemCache, billingCacheService, client, apiKeyAuthCacheInvalidator)
	secretEncryptor, err := repository.NewAESEncryptor(configConfig)
	if err != nil {
		return nil, err
	}
	totpCache := repository.NewTotpCache(redisClient)
	totpService := service.NewTotpService(userRepository, secretEncryptor, totpCache, settingService, emailService, emailQueueService)
	authHandler := handler.NewAuthHandler(configConfig, authService, userService, settingService, promoService, redeemService, totpService)
	v := repository.NewEphemeralStateStore(redisClient)
	oidcProviderService, err := service.NewOIDCProviderService(configConfig, v, userService)
	if err != nil {
		return nil, err
	}
	oidcProviderHandler := handler.NewOIDCProviderHandler(oidcProviderService)
	userHandler := handler.NewUserHandler(userService, authService, emailService, emailCache, affiliateService)
	apiKeyHandler := handler.NewAPIKeyHandler(apiKeyService)
	accountShareModeRepository := repository.NewAccountShareModeRepository(client, db, configConfig)
	openAIOAuthClient := repository.NewOpenAIOAuthClient()
	privacyClientFactory := providePrivacyClientFactory()
	openAIOAuthService := service.ProvideOpenAIOAuthService(configConfig, proxyRepository, openAIOAuthClient, privacyClientFactory)
	claudeOAuthClient := repository.NewClaudeOAuthClient()
	oAuthService := service.NewOAuthService(proxyRepository, claudeOAuthClient)
	geminiTokenCache := repository.NewGeminiTokenCache(redisClient)
	geminiOAuthClient := repository.NewGeminiOAuthClient(configConfig)
	geminiCliCodeAssistClient := repository.NewGeminiCliCodeAssistClient()
	driveClient := repository.NewGeminiDriveClient()
	geminiOAuthService := service.NewGeminiOAuthService(proxyRepository, geminiOAuthClient, geminiCliCodeAssistClient, driveClient, configConfig)
	oAuthRefreshAPI := service.ProvideOAuthRefreshAPI(accountRepository, geminiTokenCache)
	geminiTokenProvider := service.ProvideGeminiTokenProvider(accountRepository, geminiTokenCache, geminiOAuthService, oAuthRefreshAPI)
	claudeTokenProvider := service.ProvideClaudeTokenProvider(accountRepository, geminiTokenCache, oAuthService, oAuthRefreshAPI)
	gatewayCache := repository.NewGatewayCache(redisClient)
	schedulerOutboxRepository := repository.NewSchedulerOutboxRepository(db)
	schedulerSnapshotService := service.ProvideSchedulerSnapshotService(schedulerCache, schedulerOutboxRepository, accountRepository, groupRepository, settingRepository, configConfig)
	antigravityOAuthService := service.NewAntigravityOAuthService(proxyRepository)
	tempUnschedCache := repository.NewTempUnschedCache(redisClient)
	antigravityTokenProvider := service.ProvideAntigravityTokenProvider(accountRepository, geminiTokenCache, antigravityOAuthService, oAuthRefreshAPI, tempUnschedCache)
	geminiQuotaService := service.NewGeminiQuotaService(configConfig, settingRepository)
	timeoutCounterCache := repository.NewTimeoutCounterCache(redisClient)
	openAI403CounterCache := repository.NewOpenAI403CounterCache(redisClient)
	compositeTokenCacheInvalidator := service.NewCompositeTokenCacheInvalidator(geminiTokenCache)
	grokOAuthClient, err := repository.NewGrokOAuthClient()
	if err != nil {
		return nil, err
	}
	grokOAuthService := service.ProvideGrokOAuthService(proxyRepository, grokOAuthClient, v, configConfig)
	grokTokenProvider := service.ProvideGrokTokenProvider(accountRepository, geminiTokenCache, grokOAuthService, oAuthRefreshAPI, tempUnschedCache)
	grokSchedulingBlockCleanerProxy := service.NewGrokSchedulingBlockCleanerProxy()
	rateLimitService := service.ProvideRateLimitService(accountRepository, usageLogRepository, configConfig, geminiQuotaService, tempUnschedCache, timeoutCounterCache, openAI403CounterCache, settingService, compositeTokenCacheInvalidator, grokTokenProvider, grokSchedulingBlockCleanerProxy)
	httpUpstream := repository.NewHTTPUpstream(configConfig)
	internal500CounterCache := repository.NewInternal500CounterCache(redisClient)
	antigravityGatewayService := service.NewAntigravityGatewayService(accountRepository, gatewayCache, schedulerSnapshotService, antigravityTokenProvider, rateLimitService, httpUpstream, settingService, internal500CounterCache)
	tlsFingerprintProfileRepository := repository.NewTLSFingerprintProfileRepository(client)
	tlsFingerprintProfileCache := repository.NewTLSFingerprintProfileCache(redisClient)
	tlsFingerprintProfileService := service.NewTLSFingerprintProfileService(tlsFingerprintProfileRepository, tlsFingerprintProfileCache)
	agentIdentityWSInvalidatorProxy := service.NewAgentIdentityWSInvalidatorProxy()
	channelRepository := repository.NewChannelRepository(db)
	pricingRemoteClient := repository.ProvidePricingRemoteClient(configConfig)
	pricingService, err := service.ProvidePricingService(configConfig, pricingRemoteClient)
	if err != nil {
		return nil, err
	}
	channelService := service.ProvideChannelService(channelRepository, groupRepository, apiKeyAuthCacheInvalidator, pricingService, clusterCacheCoordinator)
	accountTestService := service.ProvideAccountTestService(accountRepository, geminiTokenProvider, claudeTokenProvider, antigravityGatewayService, httpUpstream, configConfig, tlsFingerprintProfileService, settingService, grokTokenProvider, agentIdentityWSInvalidatorProxy, channelService)
	billingService := service.NewBillingService(configConfig, pricingService)
	modelPricingResolver := service.NewModelPricingResolver(channelService, billingService)
	opsRepository := repository.NewOpsRepository(db)
	accountShareModeService := service.ProvideAccountShareModeService(configConfig, accountShareModeRepository, accountRepository, apiKeyRepository, usageLogRepository, userRepository, proxyRepository, openAIOAuthService, oAuthService, concurrencyService, apiKeyAuthCacheInvalidator, accountTestService, rateLimitService, billingCacheService, billingService, modelPricingResolver, channelService, settingRepository, settingService, clusterTaskExecutor, opsRepository)
	accountShareModeHandler := handler.NewAccountShareModeHandler(accountShareModeService)
	accountSharePolicyRepository := repository.NewAccountSharePolicyRepository(client, db)
	accountService := service.ProvideAccountService(accountRepository, groupRepository, userRepository, userSubscriptionRepository, proxyRepository, accountSharePolicyRepository, accountShareModeRepository, userPrivateGroupProvisioner, concurrencyService, systemNoticeService, settingService, channelService, agentIdentityWSInvalidatorProxy, accountShareModeService, rateLimitService)
	claudeUsageFetcher := repository.NewClaudeUsageFetcher(httpUpstream)
	antigravityQuotaFetcher := service.NewAntigravityQuotaFetcher(proxyRepository, configConfig)
	grokQuotaFetcher := service.NewGrokQuotaFetcher()
	grokQuotaService := service.ProvideGrokQuotaService(accountRepository, proxyRepository, grokTokenProvider, httpUpstream, usageLogRepository, configConfig, settingService)
	usageCache := service.NewUsageCache()
	identityCache := repository.NewIdentityCache(redisClient)
	accountUsageService := service.ProvideAccountUsageService(accountRepository, usageLogRepository, claudeUsageFetcher, geminiQuotaService, antigravityQuotaFetcher, grokQuotaFetcher, grokQuotaService, usageCache, identityCache, tlsFingerprintProfileService, agentIdentityWSInvalidatorProxy)
	openAITokenProvider := service.ProvideOpenAITokenProvider(accountRepository, geminiTokenCache, openAIOAuthService, oAuthRefreshAPI)
	openAIQuotaService := service.ProvideOpenAIQuotaService(accountRepository, proxyRepository, openAITokenProvider, privacyClientFactory, agentIdentityWSInvalidatorProxy)
	userContentModerationRepository := repository.NewUserContentModerationRepository(db)
	contentModerationRepository := repository.NewContentModerationRepository(db)
	contentModerationHashCache := repository.NewContentModerationHashCache(redisClient)
	contentModerationService := service.ProvideContentModerationService(settingRepository, contentModerationRepository, contentModerationHashCache, groupRepository, accountShareModeService, userContentModerationRepository, userRepository, apiKeyAuthCacheInvalidator, emailService, systemNoticeService, clusterCacheCoordinator, clusterTaskExecutor)
	userContentModerationService := service.NewUserContentModerationService(userContentModerationRepository, accountService, secretEncryptor, contentModerationService)
	sessionLimitCache := repository.ProvideSessionLimitCache(redisClient, configConfig)
	rpmCache := repository.NewRPMCache(redisClient)
	accountBatchTaskRepository := repository.NewAccountBatchTaskRepository(db)
	timingWheelService, err := service.ProvideTimingWheelService()
	if err != nil {
		return nil, err
	}
	accountBatchTaskService := service.ProvideAccountBatchTaskService(accountBatchTaskRepository, timingWheelService, clusterTaskExecutor)
	cnProviderQuotaService := service.ProvideCNProviderQuotaService(accountRepository, proxyRepository, httpUpstream, configConfig, settingService)
	cnProviderBalanceService := service.ProvideCNProviderBalanceService(accountRepository, proxyRepository, httpUpstream, configConfig, settingService)
	userAccountHandler := handler.ProvideUserAccountHandler(accountService, accountUsageService, accountTestService, rateLimitService, settingService, oAuthService, openAIOAuthService, openAIQuotaService, userContentModerationService, geminiOAuthService, antigravityOAuthService, grokOAuthService, grokTokenProvider, concurrencyService, sessionLimitCache, rpmCache, accountBatchTaskService, cnProviderQuotaService, cnProviderBalanceService)
	usageService := service.NewUsageService(usageLogRepository, userRepository, client, apiKeyAuthCacheInvalidator)
	usageHandler := handler.NewUsageHandler(usageService, apiKeyService)
	redeemHandler := handler.NewRedeemHandler(redeemService)
	subscriptionHandler := handler.NewSubscriptionHandler(subscriptionService)
	announcementRepository := repository.NewAnnouncementRepository(client)
	announcementReadRepository := repository.NewAnnouncementReadRepository(client)
	announcementService := service.ProvideAnnouncementService(announcementRepository, announcementReadRepository, userRepository, userSubscriptionRepository, systemNoticeService)
	announcementHandler := handler.NewAnnouncementHandler(announcementService)
	conversationHandler := handler.NewConversationHandler(conversationService)
	channelMonitorRepository := repository.NewChannelMonitorRepository(client, db)
	channelMonitorService := service.ProvideChannelMonitorService(channelMonitorRepository, secretEncryptor)
	groupCapacityService := service.NewGroupCapacityService(accountRepository, groupRepository, concurrencyService, sessionLimitCache, rpmCache)
	channelMonitorUserHandler := handler.NewChannelMonitorUserHandler(channelMonitorService, settingService, groupCapacityService)
	dashboardAggregationRepository := repository.NewDashboardAggregationRepository(db)
	dashboardStatsCache := repository.NewDashboardCache(redisClient, configConfig)
	dashboardService := service.NewDashboardService(usageLogRepository, dashboardAggregationRepository, dashboardStatsCache, configConfig)
	dashboardAggregationService := service.ProvideDashboardAggregationService(dashboardAggregationRepository, timingWheelService, configConfig, clusterTaskExecutor)
	dashboardHandler := admin.NewDashboardHandler(dashboardService, dashboardAggregationService)
	proxyExitInfoProber := repository.NewProxyExitInfoProber(configConfig)
	proxyLatencyCache := repository.NewProxyLatencyCache(redisClient)
	adminService := service.ProvideAdminService(userRepository, groupRepository, accountRepository, proxyRepository, apiKeyRepository, accountShareAPIKeyBindingChecker, redeemCodeRepository, userGroupRateRepository, userRPMCache, billingCacheService, proxyExitInfoProber, proxyLatencyCache, apiKeyAuthCacheInvalidator, client, settingService, subscriptionService, userSubscriptionRepository, privacyClientFactory, userPrivateGroupProvisioner, systemNoticeService, agentIdentityWSInvalidatorProxy, rateLimitService, channelService)
	adminUserHandler := admin.NewUserHandler(adminService, concurrencyService)
	groupRateScheduleRepository := repository.NewGroupRateScheduleRepository(db)
	groupRateScheduleService := service.ProvideGroupRateScheduleService(groupRateScheduleRepository, groupRepository, apiKeyAuthCacheInvalidator, apiKeyRepository, userSubscriptionRepository, userGroupRateRepository, systemNoticeService, clusterTaskExecutor)
	groupHandler := admin.NewGroupHandler(adminService, dashboardService, groupCapacityService, groupRateScheduleService)
	crsSyncService := service.NewCRSSyncService(accountRepository, proxyRepository, oAuthService, openAIOAuthService, geminiOAuthService, configConfig)
	accountHandler := handler.ProvideAdminAccountHandler(adminService, accountService, oAuthService, openAIOAuthService, geminiOAuthService, antigravityOAuthService, grokOAuthService, grokTokenProvider, rateLimitService, accountUsageService, accountTestService, concurrencyService, crsSyncService, sessionLimitCache, rpmCache, compositeTokenCacheInvalidator, accountBatchTaskService, grokQuotaService, cnProviderQuotaService, cnProviderBalanceService)
	accountSharePolicyService := service.NewAccountSharePolicyService(accountSharePolicyRepository)
	accountSharePolicyHandler := admin.NewAccountSharePolicyHandler(accountSharePolicyService)
	adminAnnouncementHandler := admin.NewAnnouncementHandler(announcementService)
	adminConversationHandler := admin.NewConversationHandler(conversationService)
	dataManagementService := service.NewDataManagementService()
	dataManagementHandler := admin.NewDataManagementHandler(dataManagementService)
	backupObjectStoreFactory := repository.NewS3BackupStoreFactory()
	dbDumper := repository.NewPgDumper(configConfig)
	backupService := service.ProvideBackupService(settingRepository, configConfig, secretEncryptor, backupObjectStoreFactory, dbDumper, clusterTaskExecutor)
	backupHandler := admin.NewBackupHandler(backupService, userService)
	oAuthHandler := admin.NewOAuthHandler(oAuthService)
	openAIOAuthHandler := admin.NewOpenAIOAuthHandler(openAIOAuthService, adminService, openAIQuotaService)
	geminiOAuthHandler := admin.NewGeminiOAuthHandler(geminiOAuthService)
	antigravityOAuthHandler := admin.NewAntigravityOAuthHandler(antigravityOAuthService)
	tokenRefreshService := service.ProvideTokenRefreshService(accountRepository, oAuthService, openAIOAuthService, geminiOAuthService, antigravityOAuthService, grokOAuthService, compositeTokenCacheInvalidator, schedulerCache, configConfig, tempUnschedCache, privacyClientFactory, proxyRepository, oAuthRefreshAPI, clusterTaskExecutor)
	grokOAuthHandler := handler.ProvideGrokOAuthHandler(grokOAuthService, grokTokenProvider, adminService, grokQuotaService, tokenRefreshService)
	proxyHandler := admin.NewProxyHandler(adminService)
	adminRedeemHandler := admin.NewRedeemHandler(adminService, redeemService)
	promoHandler := admin.NewPromoHandler(promoService)
	usageBillingRepository := repository.NewUsageBillingRepository(client, db)
	identityService := service.NewIdentityService(identityCache)
	deferredService := service.ProvideDeferredService(accountRepository, timingWheelService)
	digestSessionStore := service.NewDigestSessionStore()
	balanceNotifyService := service.ProvideBalanceNotifyService(emailService, settingRepository, accountRepository)
	gatewayService := service.ProvideGatewayService(accountRepository, accountSharePolicyRepository, groupRepository, usageLogRepository, usageBillingRepository, userRepository, userSubscriptionRepository, userGroupRateRepository, gatewayCache, configConfig, schedulerSnapshotService, concurrencyService, billingService, rateLimitService, billingCacheService, identityService, httpUpstream, deferredService, claudeTokenProvider, sessionLimitCache, rpmCache, digestSessionStore, settingService, tlsFingerprintProfileService, channelService, modelPricingResolver, balanceNotifyService, accountShareModeService)
	v2 := service.ProvideAccountShareModeServices(accountShareModeService)
	openAIGatewayService := service.ProvideOpenAIGatewayService(accountRepository, accountSharePolicyRepository, usageLogRepository, usageBillingRepository, userRepository, userSubscriptionRepository, userGroupRateRepository, gatewayCache, configConfig, schedulerSnapshotService, concurrencyService, billingService, rateLimitService, billingCacheService, httpUpstream, deferredService, openAITokenProvider, grokTokenProvider, modelPricingResolver, channelService, balanceNotifyService, settingService, accountService, agentIdentityWSInvalidatorProxy, grokSchedulingBlockCleanerProxy, accountUsageService, tlsFingerprintProfileService, v2...)
	geminiMessagesCompatService := service.NewGeminiMessagesCompatService(accountRepository, groupRepository, gatewayCache, schedulerSnapshotService, geminiTokenProvider, rateLimitService, httpUpstream, antigravityGatewayService, configConfig, settingService)
	opsSystemLogSink := service.ProvideOpsSystemLogSink(opsRepository, configConfig)
	opsService := service.NewOpsService(opsRepository, settingRepository, configConfig, accountRepository, userRepository, concurrencyService, gatewayService, openAIGatewayService, geminiMessagesCompatService, antigravityGatewayService, opsSystemLogSink)
	encryptionKey, err := payment.ProvideEncryptionKey(configConfig)
	if err != nil {
		return nil, err
	}
	paymentConfigService := service.ProvidePaymentConfigService(client, settingRepository, encryptionKey, configConfig)
	registry := payment.ProvideRegistry()
	defaultLoadBalancer := payment.ProvideDefaultLoadBalancer(client, encryptionKey)
	paymentService := service.ProvidePaymentService(client, registry, defaultLoadBalancer, redeemService, subscriptionService, paymentConfigService, userRepository, groupRepository, affiliateService, systemNoticeService)
	settingHandler := admin.NewSettingHandler(settingService, emailService, turnstileService, opsService, paymentConfigService, paymentService)
	opsHandler := admin.NewOpsHandler(opsService)
	clusterService := service.NewClusterService(clusterAdminRepository, configConfig)
	clusterHandler := admin.NewClusterHandler(clusterService)
	updateCache := repository.NewUpdateCache(redisClient)
	gitHubReleaseClient := repository.ProvideGitHubReleaseClient(configConfig)
	serviceBuildInfo := provideServiceBuildInfo(buildInfo)
	updateService := service.ProvideUpdateService(updateCache, gitHubReleaseClient, serviceBuildInfo)
	idempotencyRepository := repository.NewIdempotencyRepository(client, db)
	systemOperationLockService := service.ProvideSystemOperationLockService(idempotencyRepository, configConfig)
	systemHandler := handler.ProvideSystemHandler(updateService, systemOperationLockService)
	adminSubscriptionHandler := admin.NewSubscriptionHandler(subscriptionService)
	usageCleanupRepository := repository.NewUsageCleanupRepository(client, db)
	usageCleanupService := service.ProvideUsageCleanupService(usageCleanupRepository, timingWheelService, dashboardAggregationService, backupService, settingRepository, configConfig, clusterTaskExecutor)
	adminUsageHandler := admin.NewUsageHandler(usageService, apiKeyService, adminService, usageCleanupService)
	userAttributeDefinitionRepository := repository.NewUserAttributeDefinitionRepository(client)
	userAttributeValueRepository := repository.NewUserAttributeValueRepository(client)
	userAttributeService := service.NewUserAttributeService(userAttributeDefinitionRepository, userAttributeValueRepository)
	userAttributeHandler := admin.NewUserAttributeHandler(userAttributeService)
	errorPassthroughRepository := repository.NewErrorPassthroughRepository(client)
	errorPassthroughCache := repository.NewErrorPassthroughCache(redisClient)
	errorPassthroughService := service.NewErrorPassthroughService(errorPassthroughRepository, errorPassthroughCache)
	errorPassthroughHandler := admin.NewErrorPassthroughHandler(errorPassthroughService)
	tlsFingerprintProfileHandler := admin.NewTLSFingerprintProfileHandler(tlsFingerprintProfileService)
	adminAPIKeyHandler := admin.NewAdminAPIKeyHandler(adminService)
	scheduledTestPlanRepository := repository.NewScheduledTestPlanRepository(db)
	scheduledTestResultRepository := repository.NewScheduledTestResultRepository(db)
	scheduledTestService := service.ProvideScheduledTestService(scheduledTestPlanRepository, scheduledTestResultRepository, accountTestService)
	scheduledTestHandler := admin.NewScheduledTestHandler(scheduledTestService)
	channelHandler := admin.NewChannelHandler(channelService, billingService)
	channelMonitorHandler := admin.NewChannelMonitorHandler(channelMonitorService)
	channelMonitorRequestTemplateRepository := repository.NewChannelMonitorRequestTemplateRepository(client, db)
	channelMonitorRequestTemplateService := service.NewChannelMonitorRequestTemplateService(channelMonitorRequestTemplateRepository)
	channelMonitorRequestTemplateHandler := admin.NewChannelMonitorRequestTemplateHandler(channelMonitorRequestTemplateService)
	contentModerationHandler := admin.NewContentModerationHandler(contentModerationService, v2...)
	cyberPolicyHandler := admin.NewCyberPolicyHandler(openAIGatewayService, opsService)
	paymentHandler := admin.NewPaymentHandler(paymentService, paymentConfigService)
	revenueService := service.NewRevenueService(client)
	revenueHandler := admin.NewRevenueHandler(revenueService)
	withdrawalRepository := repository.NewWithdrawalRepository(db)
	receiptCodeRepository := repository.NewReceiptCodeRepository(db)
	receiptCodeObjectStoreFactory := repository.NewReceiptCodeObjectStoreFactory()
	receiptCodeService := service.NewReceiptCodeService(receiptCodeRepository, paymentConfigService, receiptCodeObjectStoreFactory)
	withdrawalService := service.NewWithdrawalService(withdrawalRepository, apiKeyAuthCacheInvalidator, billingCacheService, receiptCodeService, systemNoticeService, settingService)
	withdrawalHandler := admin.NewWithdrawalHandler(withdrawalService)
	invoiceRepository := repository.NewInvoiceRepository(db)
	invoiceService := service.NewInvoiceService(invoiceRepository, settingService)
	invoiceHandler := admin.NewInvoiceHandler(invoiceService)
	shopFileCardObjectStoreFactory := repository.NewShopFileCardObjectStoreFactory()
	shopService := service.ProvideShopService(client, paymentService, apiKeyAuthCacheInvalidator, billingCacheService, settingRepository, encryptionKey, shopFileCardObjectStoreFactory)
	shopHandler := admin.NewShopHandler(shopService)
	affiliateHandler := admin.NewAffiliateHandler(affiliateService, adminService)
	activityService := service.NewActivityService(client, secretEncryptor, billingCacheService)
	activityHandler := admin.NewActivityHandler(activityService)
	ideasRepository := repository.NewIdeasRepository(db)
	ideasService := service.ProvideIdeasService(ideasRepository, settingService, clusterTaskExecutor)
	ideasHandler := admin.NewIdeasHandler(ideasService)
	adminHandlers := handler.ProvideAdminHandlers(dashboardHandler, adminUserHandler, groupHandler, accountHandler, accountSharePolicyHandler, adminAnnouncementHandler, adminConversationHandler, dataManagementHandler, backupHandler, oAuthHandler, openAIOAuthHandler, geminiOAuthHandler, antigravityOAuthHandler, grokOAuthHandler, proxyHandler, adminRedeemHandler, promoHandler, settingHandler, opsHandler, clusterHandler, systemHandler, adminSubscriptionHandler, adminUsageHandler, userAttributeHandler, errorPassthroughHandler, tlsFingerprintProfileHandler, adminAPIKeyHandler, scheduledTestHandler, channelHandler, channelMonitorHandler, channelMonitorRequestTemplateHandler, contentModerationHandler, cyberPolicyHandler, paymentHandler, revenueHandler, withdrawalHandler, invoiceHandler, shopHandler, affiliateHandler, activityHandler, ideasHandler)
	usageRecordWorkerPool := service.NewUsageRecordWorkerPool(configConfig)
	userMsgQueueCache := repository.NewUserMsgQueueCache(redisClient)
	userMessageQueueService := service.ProvideUserMessageQueueService(userMsgQueueCache, rpmCache, configConfig, clusterTaskExecutor)
	noAccountBackoffLimiter := repository.NewNoAccountBackoffCache(redisClient, configConfig)
	devinGatewayService := service.NewDevinGatewayService(openAIGatewayService, accountService, configConfig)
	gatewayHandler := handler.NewGatewayHandler(gatewayService, geminiMessagesCompatService, antigravityGatewayService, userService, concurrencyService, billingCacheService, usageService, apiKeyService, usageRecordWorkerPool, errorPassthroughService, contentModerationService, userContentModerationService, userMessageQueueService, noAccountBackoffLimiter, devinGatewayService, configConfig, settingService)
	openAIGatewayHandler := handler.ProvideOpenAIGatewayHandler(openAIGatewayService, devinGatewayService, concurrencyService, billingCacheService, apiKeyService, usageRecordWorkerPool, errorPassthroughService, contentModerationService, userContentModerationService, grokQuotaService, noAccountBackoffLimiter, configConfig)
	handlerSettingHandler := handler.ProvideSettingHandler(settingService, buildInfo)
	totpHandler := handler.NewTotpHandler(totpService)
	handlerPaymentHandler := handler.NewPaymentHandler(paymentService, paymentConfigService)
	paymentWebhookHandler := handler.NewPaymentWebhookHandler(paymentService, registry)
	availableChannelHandler := handler.NewAvailableChannelHandler(channelService, apiKeyService, settingService)
	receiptCodeHandler := handler.NewReceiptCodeHandler(receiptCodeService)
	handlerWithdrawalHandler := handler.NewWithdrawalHandler(withdrawalService)
	handlerInvoiceHandler := handler.NewInvoiceHandler(invoiceService)
	handlerShopHandler := handler.NewShopHandler(shopService)
	handlerActivityHandler := handler.NewActivityHandler(activityService)
	handlerIdeasHandler := handler.NewIdeasHandler(ideasService)
	idempotencyCoordinator := service.ProvideIdempotencyCoordinator(idempotencyRepository, configConfig)
	idempotencyCleanupService := service.ProvideIdempotencyCleanupService(idempotencyRepository, configConfig, clusterTaskExecutor)
	v3 := service.ProvideAccountBatchTaskServices(accountBatchTaskService)
	handlers := handler.ProvideHandlers(authHandler, oidcProviderHandler, userHandler, apiKeyHandler, accountShareModeHandler, userAccountHandler, usageHandler, redeemHandler, subscriptionHandler, announcementHandler, conversationHandler, channelMonitorUserHandler, adminHandlers, gatewayHandler, openAIGatewayHandler, handlerSettingHandler, totpHandler, handlerPaymentHandler, paymentWebhookHandler, availableChannelHandler, receiptCodeHandler, handlerWithdrawalHandler, handlerInvoiceHandler, handlerShopHandler, handlerActivityHandler, handlerIdeasHandler, idempotencyCoordinator, idempotencyCleanupService, v3)
	jwtAuthMiddleware := middleware.NewJWTAuthMiddleware(authService, userService)
	adminAuthMiddleware := middleware.NewAdminAuthMiddleware(authService, userService, settingService)
	apiKeyAuthMiddleware := middleware.NewAPIKeyAuthMiddleware(apiKeyService, subscriptionService, configConfig)
	clusterRedisPort := repository.NewClusterRedisPort(redisClient)
	clusterConnectionTracker := service.NewClusterConnectionTracker()
	clusterRuntime, err := service.NewClusterRuntime(configConfig, clusterRepository, db, clusterRedisPort, clusterConnectionTracker, clusterNodeState, clusterCacheCoordinator, clusterTaskExecutor, serviceBuildInfo, channelService, settingService, contentModerationService)
	if err != nil {
		return nil, err
	}
	engine := server.ProvideRouter(configConfig, handlers, jwtAuthMiddleware, adminAuthMiddleware, apiKeyAuthMiddleware, apiKeyService, subscriptionService, opsService, settingService, clusterRuntime, redisClient)
	httpServer := server.ProvideHTTPServer(configConfig, engine, clusterConnectionTracker)
	opsMetricsCollector := service.ProvideOpsMetricsCollector(opsRepository, settingRepository, accountRepository, concurrencyService, db, redisClient, configConfig, clusterTaskExecutor)
	opsAggregationService := service.ProvideOpsAggregationService(opsRepository, settingRepository, db, redisClient, configConfig, clusterTaskExecutor)
	proxyExpiryMetricsRepository, err := service.ProvideProxyExpiryMetricsRepository(proxyRepository)
	if err != nil {
		return nil, err
	}
	opsAlertEvaluatorService := service.ProvideOpsAlertEvaluatorService(opsService, opsRepository, emailService, redisClient, configConfig, clusterTaskExecutor, proxyExpiryMetricsRepository)
	opsCleanupService := service.ProvideOpsCleanupService(opsService, opsRepository, settingRepository, db, redisClient, configConfig, channelMonitorService, backupService, clusterTaskExecutor)
	opsScheduledReportService := service.ProvideOpsScheduledReportService(opsService, userService, emailService, redisClient, configConfig, clusterTaskExecutor)
	affiliateCodeCycleService := service.ProvideAffiliateCodeCycleService(affiliateService, clusterTaskExecutor)
	accountExpiryService := service.ProvideAccountExpiryService(accountRepository, clusterTaskExecutor)
	cnProviderBalanceCheckService := service.ProvideCNProviderBalanceCheckService(accountRepository, cnProviderBalanceService, cnProviderQuotaService, configConfig, clusterTaskExecutor)
	proxyExpirySweeper, err := service.ProvideProxyExpirySweeper(proxyRepository)
	if err != nil {
		return nil, err
	}
	proxyExpiryService := service.ProvideProxyExpiryService(proxyExpirySweeper, configConfig)
	accountErrorCleanupService := service.ProvideAccountErrorCleanupService(accountRepository, clusterTaskExecutor)
	conversationAdminReplyTimeoutService, err := service.ProvideConversationAdminReplyTimeoutService(conversationRepository, clusterTaskExecutor)
	if err != nil {
		return nil, err
	}
	subscriptionExpiryService := service.ProvideSubscriptionExpiryService(userSubscriptionRepository, clusterTaskExecutor)
	scheduledTestRunnerService := service.ProvideScheduledTestRunnerService(scheduledTestPlanRepository, scheduledTestService, accountTestService, rateLimitService, configConfig, clusterTaskExecutor)
	activityAutoDrawService := service.ProvideActivityAutoDrawService(activityService, clusterTaskExecutor)
	paymentOrderExpiryService := service.ProvidePaymentOrderExpiryService(paymentService, clusterTaskExecutor)
	channelMonitorRunner := service.ProvideChannelMonitorRunner(channelMonitorService, settingService, clusterTaskExecutor)
	v4 := provideCleanup(client, redisClient, opsMetricsCollector, opsAggregationService, opsAlertEvaluatorService, opsCleanupService, opsScheduledReportService, opsSystemLogSink, schedulerSnapshotService, groupRateScheduleService, affiliateCodeCycleService, tokenRefreshService, accountExpiryService, cnProviderBalanceCheckService, proxyExpiryService, accountErrorCleanupService, conversationAdminReplyTimeoutService, subscriptionExpiryService, usageCleanupService, idempotencyCleanupService, concurrencyService, userMessageQueueService, pricingService, emailQueueService, billingCacheService, usageRecordWorkerPool, subscriptionService, oAuthService, openAIOAuthService, geminiOAuthService, antigravityOAuthService, grokOAuthService, accountShareModeService, openAIGatewayService, scheduledTestRunnerService, backupService, activityAutoDrawService, paymentOrderExpiryService, channelMonitorRunner, contentModerationService, ideasService, clusterRuntime)
	application := &Application{
		Server:         httpServer,
		Cleanup:        v4,
		ClusterRuntime: clusterRuntime,
	}
	return application, nil
}

// wire.go:

type Application struct {
	Server         *http.Server
	Cleanup        func(context.Context) error
	ClusterRuntime *service.ClusterRuntime
}

func providePrivacyClientFactory() service.PrivacyClientFactory {
	return repository.CreatePrivacyReqClient
}

func provideServiceBuildInfo(buildInfo handler.BuildInfo) service.BuildInfo {
	return service.BuildInfo{
		Version:   buildInfo.Version,
		BuildType: buildInfo.BuildType,
		Commit:    buildInfo.Commit,
		Date:      buildInfo.Date,
	}
}

func provideCleanup(
	entClient *ent.Client,
	rdb *redis.Client,
	opsMetricsCollector *service.OpsMetricsCollector,
	opsAggregation *service.OpsAggregationService,
	opsAlertEvaluator *service.OpsAlertEvaluatorService,
	opsCleanup *service.OpsCleanupService,
	opsScheduledReport *service.OpsScheduledReportService,
	opsSystemLogSink *service.OpsSystemLogSink,
	schedulerSnapshot *service.SchedulerSnapshotService,
	groupRateSchedule *service.GroupRateScheduleService,
	affiliateCodeCycle *service.AffiliateCodeCycleService,
	tokenRefresh *service.TokenRefreshService,
	accountExpiry *service.AccountExpiryService,
	cnProviderBalanceCheck *service.CNProviderBalanceCheckService,
	proxyExpiry *service.ProxyExpiryService,
	accountErrorCleanup *service.AccountErrorCleanupService,
	conversationAdminReplyTimeout *service.ConversationAdminReplyTimeoutService,
	subscriptionExpiry *service.SubscriptionExpiryService,
	usageCleanup *service.UsageCleanupService,
	idempotencyCleanup *service.IdempotencyCleanupService,
	concurrency *service.ConcurrencyService,
	userMessageQueue *service.UserMessageQueueService,
	pricing *service.PricingService,
	emailQueue *service.EmailQueueService,
	billingCache *service.BillingCacheService,
	usageRecordWorkerPool *service.UsageRecordWorkerPool,
	subscriptionService *service.SubscriptionService,
	oauth *service.OAuthService,
	openaiOAuth *service.OpenAIOAuthService,
	geminiOAuth *service.GeminiOAuthService,
	antigravityOAuth *service.AntigravityOAuthService,
	grokOAuth *service.GrokOAuthService,
	accountShareMode *service.AccountShareModeService,
	openAIGateway *service.OpenAIGatewayService,
	scheduledTestRunner *service.ScheduledTestRunnerService,
	backupSvc *service.BackupService,
	activityAutoDraw *service.ActivityAutoDrawService,
	paymentOrderExpiry *service.PaymentOrderExpiryService,
	channelMonitorRunner *service.ChannelMonitorRunner,
	contentModeration *service.ContentModerationService,
	ideasService *service.IdeasService,
	clusterRuntime *service.ClusterRuntime,
) func(context.Context) error {
	return func(ctx context.Context) error {

		parallelSteps := []cleanupStep{
			{"ClusterRuntime", func() error {
				if clusterRuntime != nil {
					return clusterRuntime.Stop(ctx)
				}
				return nil
			}},
			{"OpsScheduledReportService", func() error {
				if opsScheduledReport != nil {
					opsScheduledReport.Stop()
				}
				return nil
			}},
			{"OpsCleanupService", func() error {
				if opsCleanup != nil {
					opsCleanup.Stop()
				}
				return nil
			}},
			{"OpsSystemLogSink", func() error {
				if opsSystemLogSink != nil {
					opsSystemLogSink.Stop()
				}
				return nil
			}},
			{"OpsAlertEvaluatorService", func() error {
				if opsAlertEvaluator != nil {
					opsAlertEvaluator.Stop()
				}
				return nil
			}},
			{"OpsAggregationService", func() error {
				if opsAggregation != nil {
					opsAggregation.Stop()
				}
				return nil
			}},
			{"OpsMetricsCollector", func() error {
				if opsMetricsCollector != nil {
					opsMetricsCollector.Stop()
				}
				return nil
			}},
			{"SchedulerSnapshotService", func() error {
				if schedulerSnapshot != nil {
					schedulerSnapshot.Stop()
				}
				return nil
			}},
			{"GroupRateScheduleService", func() error {
				if groupRateSchedule != nil {
					groupRateSchedule.Stop()
				}
				return nil
			}},
			{"AffiliateCodeCycleService", func() error {
				if affiliateCodeCycle != nil {
					affiliateCodeCycle.Stop()
				}
				return nil
			}},
			{"UsageCleanupService", func() error {
				if usageCleanup != nil {
					usageCleanup.Stop()
				}
				return nil
			}},
			{"IdempotencyCleanupService", func() error {
				if idempotencyCleanup != nil {
					idempotencyCleanup.Stop()
				}
				return nil
			}},
			{"TokenRefreshService", func() error {
				tokenRefresh.Stop()
				return nil
			}},
			{"AccountExpiryService", func() error {
				accountExpiry.Stop()
				return nil
			}},
			{"CNProviderBalanceCheckService", func() error {
				if cnProviderBalanceCheck != nil {
					cnProviderBalanceCheck.Stop()
				}
				return nil
			}},
			{"ProxyExpiryService", func() error {
				if proxyExpiry != nil {
					proxyExpiry.Stop()
				}
				return nil
			}},
			{"AccountErrorCleanupService", func() error {
				if accountErrorCleanup != nil {
					accountErrorCleanup.Stop()
				}
				return nil
			}},
			{"ConversationAdminReplyTimeoutService", func() error {
				if conversationAdminReplyTimeout != nil {
					conversationAdminReplyTimeout.Stop()
				}
				return nil
			}},
			{"SubscriptionExpiryService", func() error {
				subscriptionExpiry.Stop()
				return nil
			}},
			{"ConcurrencyService", func() error {
				if concurrency != nil {
					concurrency.Stop()
				}
				return nil
			}},
			{"UserMessageQueueService", func() error {
				if userMessageQueue != nil {
					userMessageQueue.Stop()
				}
				return nil
			}},
			{"SubscriptionService", func() error {
				if subscriptionService != nil {
					subscriptionService.Stop()
				}
				return nil
			}},
			{"PricingService", func() error {
				pricing.Stop()
				return nil
			}},
			{"EmailQueueService", func() error {
				emailQueue.Stop()
				return nil
			}},
			{"BillingCacheService", func() error {
				billingCache.Stop()
				return nil
			}},
			{"UsageRecordWorkerPool", func() error {
				if usageRecordWorkerPool != nil {
					usageRecordWorkerPool.Stop()
				}
				return nil
			}},
			{"OAuthService", func() error {
				oauth.Stop()
				return nil
			}},
			{"OpenAIOAuthService", func() error {
				openaiOAuth.Stop()
				return nil
			}},
			{"GeminiOAuthService", func() error {
				geminiOAuth.Stop()
				return nil
			}},
			{"AntigravityOAuthService", func() error {
				antigravityOAuth.Stop()
				return nil
			}},
			{"GrokOAuthService", func() error {
				if grokOAuth != nil {
					grokOAuth.Stop()
				}
				return nil
			}},
			{"AccountShareModeService", func() error {
				if accountShareMode != nil {
					accountShareMode.StopReviewModerationWorker()
					accountShareMode.StopSeatBillingWorker()
				}
				return nil
			}},
			{"OpenAIWSPool", func() error {
				if openAIGateway != nil {
					openAIGateway.CloseOpenAIWSPool()
				}
				return nil
			}},
			{"ScheduledTestRunnerService", func() error {
				if scheduledTestRunner != nil {
					scheduledTestRunner.Stop()
				}
				return nil
			}},
			{"BackupService", func() error {
				if backupSvc != nil {
					backupSvc.Stop()
				}
				return nil
			}},
			{"ActivityAutoDrawService", func() error {
				if activityAutoDraw != nil {
					activityAutoDraw.Stop()
				}
				return nil
			}},
			{"PaymentOrderExpiryService", func() error {
				if paymentOrderExpiry != nil {
					paymentOrderExpiry.Stop()
				}
				return nil
			}},
			{"ChannelMonitorRunner", func() error {
				if channelMonitorRunner != nil {
					channelMonitorRunner.Stop()
				}
				return nil
			}},
			{"ContentModerationCleanup", func() error {
				if contentModeration != nil {
					contentModeration.StopCleanupWorker()
				}
				return nil
			}},
			{"IdeasModeration", func() error {
				if ideasService != nil {
					ideasService.StopModerationWorker()
				}
				return nil
			}},
		}

		infraSteps := []cleanupStep{
			{"Redis", func() error {
				if rdb == nil {
					return nil
				}
				return rdb.Close()
			}},
			{"Ent", func() error {
				if entClient == nil {
					return nil
				}
				return entClient.Close()
			}},
		}

		return runProcessCleanup(ctx, parallelSteps, infraSteps)
	}
}
